"""Was the prompt tuned on the test set? The v1-vs-v2 descriptions choice, re-run on train (7.5)

    python scripts/label.py --split train --seed 0 --limit 200 --top-k 3 \\
        --descriptions-file data/intent_descriptions_v1.json --run desc_v1   # jobs.py does this
    python scripts/descriptions_check.py

The teacher's prompt settings were chosen on 200 *test* queries (v1 descriptions 0.885 → v2
0.905 there), which is a leak: the reported test accuracy may flatter a prompt picked on it.
This re-asks the question on 200 *train* queries that played no part in the choice:

- **v2 arm**: the first 200 rows of `train.jsonl`, already labelled with v2 descriptions,
  top-3, reasoning low (file order is the labeller's seed-0 shuffle, so they are a random
  sample, in the same batches of 20).
- **v1 arm**: the same 200 queries, same batches, same settings, v1 descriptions
  (`train.desc_v1.jsonl`).

If v2 still wins on train, choosing it on test did not matter. The v2 descriptions were written
after reading three random train queries per intent (231 of 10,003, not recorded), so about 5 of
these 200 may be among them.

Writes results/descriptions_check.json and docs/descriptions_check.md.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from distilroute.data import DOCS, LABELS, RESULTS, load_labels, load_split, rel  # noqa: E402

N = 200
TEST_GATE = {"v1": 0.885, "v2": 0.905}  # 2026-09-18, the 200 test queries (ROADMAP session log)


def main() -> None:
    if not (LABELS / "train.desc_v1.jsonl").exists():
        sys.exit("train.desc_v1.jsonl not found: run the groq lane of scripts/jobs.py first")
    first = [
        json.loads(line)["idx"]
        for line in (LABELS / "train.jsonl").open(encoding="utf-8")
        if line.strip()
    ][:N]
    v2 = load_labels("train").loc[first]
    v1 = load_labels("train.desc_v1")
    idx = [i for i in first if i in v1.index]
    if len(idx) < N:
        sys.exit(f"v1 arm has {len(idx)} of the {N} queries; let jobs.py finish it")
    gold = load_split("train").category.reindex(idx).values
    a1, a2 = v1.loc[idx].teacher.values, v2.loc[idx].teacher.values
    ok1, ok2 = a1 == gold, a2 == gold
    # Paired bootstrap of the v2 - v1 gap over these queries.
    rng = np.random.default_rng(0)
    diffs = [
        float(ok2[s].mean() - ok1[s].mean())
        for s in (rng.integers(0, len(idx), len(idx)) for _ in range(10_000))
    ]
    out = {
        "n": len(idx),
        "v1": float(ok1.mean()),
        "v2": float(ok2.mean()),
        "gap": float(ok2.mean() - ok1.mean()),
        "gap_ci95": [float(np.quantile(diffs, 0.025)), float(np.quantile(diffs, 0.975))],
        "v2_ahead_share": float(np.mean(np.array(diffs) > 0)),
        "only_v2_right": int((ok2 & ~ok1).sum()),
        "only_v1_right": int((ok1 & ~ok2).sum()),
        "test_gate": TEST_GATE,
    }
    RESULTS.mkdir(parents=True, exist_ok=True)
    (RESULTS / "descriptions_check.json").write_text(json.dumps(out, indent=2) + "\n")

    lo, hi = out["gap_ci95"]
    lines = [
        "# Was the prompt tuned on the test set?",
        "",
        "_Generated by `scripts/descriptions_check.py`. The teacher's intent descriptions (v1, "
        "then v2) were chosen on 200 test queries. Here the same choice is re-run on "
        f"{out['n']} train queries that played no part in it: same batches, same settings "
        "(gpt-oss-120b, top-3, reasoning low); only the descriptions differ. Accuracy vs gold._",
        "",
        "| descriptions | on 200 test queries (where it was chosen) | "
        f"on {out['n']} train queries (fresh) |",
        "|---|---:|---:|",
        f"| v1 | {TEST_GATE['v1']:.3f} | {out['v1']:.3f} |",
        f"| v2 | {TEST_GATE['v2']:.3f} | {out['v2']:.3f} |",
        f"| v2 − v1 | {(TEST_GATE['v2'] - TEST_GATE['v1']) * 100:+.1f} pt | "
        f"**{out['gap'] * 100:+.1f} pt** (95 % {lo * 100:+.1f} to {hi * 100:+.1f}) |",
        "",
        f"On train, v2 is right where v1 is wrong on {out['only_v2_right']} queries, and the "
        f"reverse on {out['only_v1_right']}; v2 is ahead in {out['v2_ahead_share']:.0%} of "
        "10,000 paired resamples. "
        + (
            "**The choice holds on data it was not made on**, so picking it on test did not "
            "inflate the reported teacher accuracy beyond noise."
            if lo > 0
            else "The gap on train is within noise, so the test-set choice cannot be confirmed "
            "on fresh data; treat the teacher's reported accuracy as possibly flattered by it."
        ),
        "",
        "**Caveat.** The v2 descriptions were written after reading three random train queries "
        "per intent (231 of 10,003, not recorded), so about 5 of these 200 may be among them. "
        "The test-gate numbers were top-1; the train arms are top-3, the production setting.",
    ]
    DOCS.mkdir(parents=True, exist_ok=True)
    (DOCS / "descriptions_check.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    print(f"-> {rel(RESULTS)}/descriptions_check.json, {rel(DOCS)}/descriptions_check.md")


if __name__ == "__main__":
    main()
