"""A second, independent LLM teacher on the same 200 test queries (roadmap 7.5, was 1b.6).

    python scripts/label.py --provider gemini --split test --limit 200 --seed 1 \\
        --descriptions --top-k 3 --run gate_gemini                     # jobs.py's gemini lane
    python scripts/second_teacher.py                                   # compare

Two questions, both about the teacher rather than the students:

- **Which free teacher is better?** Accuracy and top-3 accuracy of each against gold, on the
  same 200 queries, same prompt (v2 intent descriptions, ranked top-3).
- **Is agreement a noise signal?** Where two independent LLMs give the same label, is it more
  often right? If so, a second teacher is a label-quality filter that costs one more LLM pass
  instead of a human: keep the rows both agree on, send the rest to review. Reported: the share
  of rows they agree on, accuracy on those vs on the rest, and how many of the first teacher's
  errors land in the disagreement set (what a reviewer looking only there would catch).

The first teacher is `test.gate_v2_top3` (gpt-oss-120b on Groq, the project's teacher config).
Writes results/second_teacher.json and docs/second_teacher.md.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from distilroute.data import DOCS, LABELS, RESULTS, load_labels, load_split, rel  # noqa: E402


def describe(df) -> str:
    row = df.iloc[0]
    return f"{row.get('model')} ({row.get('provider')})"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--a", default="test.gate_v2_top3", help="the project's teacher")
    ap.add_argument("--b", default="test.gate_gemini", help="the second teacher")
    args = ap.parse_args()
    if not (LABELS / f"{args.b}.jsonl").exists():
        sys.exit(f"{args.b}.jsonl not found: run the gemini lane of scripts/jobs.py first")

    a, b = load_labels(args.a), load_labels(args.b)
    idx = a.index.intersection(b.index)
    a, b = a.loc[idx], b.loc[idx]
    gold = load_split("test").category.reindex(idx).values
    ya, yb = a.teacher.values, b.teacher.values
    ok_a, ok_b = ya == gold, yb == gold
    agree = ya == yb
    top3 = {
        name: float(np.mean([g in list(r)[:3] for g, r in zip(gold, df.ranked, strict=True)]))
        for name, df in (("a", a), ("b", b))
    }
    out = {
        "a": {"file": args.a, "model": describe(a), "acc": float(ok_a.mean()), "top3": top3["a"]},
        "b": {"file": args.b, "model": describe(b), "acc": float(ok_b.mean()), "top3": top3["b"]},
        "n": int(len(idx)),
        "unparsed_b": int(b.teacher.isna().sum()),
        "agree": float(agree.mean()),
        "acc_when_agree": float(ok_a[agree].mean()) if agree.any() else None,
        "acc_a_when_disagree": float(ok_a[~agree].mean()) if (~agree).any() else None,
        "acc_b_when_disagree": float(ok_b[~agree].mean()) if (~agree).any() else None,
        "either_right": float((ok_a | ok_b).mean()),
        "a_errors": int((~ok_a).sum()),
        "a_errors_in_disagreement": int((~ok_a & ~agree).sum()),
    }
    RESULTS.mkdir(parents=True, exist_ok=True)
    (RESULTS / "second_teacher.json").write_text(json.dumps(out, indent=2) + "\n")
    write_doc(out)
    for k, v in out.items():
        print(f"  {k:26} {v}")
    print(f"-> {rel(RESULTS)}/second_teacher.json, {rel(DOCS)}/second_teacher.md")


def write_doc(o: dict) -> None:
    a, b = o["a"], o["b"]
    caught = o["a_errors_in_disagreement"] / o["a_errors"] if o["a_errors"] else 0.0
    lines = [
        "# A second teacher",
        "",
        f"_Generated by `scripts/second_teacher.py`. The same {o['n']} Banking77 test queries "
        "(seed 1), the same prompt (v2 intent descriptions, ranked top-3), two LLMs; accuracy vs "
        "gold._",
        "",
        "| teacher | accuracy | gold in top-3 |",
        "|---|---:|---:|",
        f"| {a['model']} — the project's teacher | {a['acc']:.3f} | {a['top3']:.3f} |",
        f"| {b['model']} | {b['acc']:.3f} | {b['top3']:.3f} |",
        "",
        f"{b['model']} left {o['unparsed_b']} of {o['n']} answers unparseable (counted wrong).",
        "",
        "## Agreement as a noise signal",
        "",
        "| | rows | accuracy |",
        "|---|---:|---:|",
        f"| both give the same label | {o['agree']:.0%} | **{o['acc_when_agree']:.3f}** |",
        f"| they disagree — first teacher | {1 - o['agree']:.0%} | "
        f"{o['acc_a_when_disagree']:.3f} |",
        f"| they disagree — second teacher | | {o['acc_b_when_disagree']:.3f} |",
        f"| either one right | 100% | {o['either_right']:.3f} |",
        "",
        f"Of the first teacher's {o['a_errors']} errors, {o['a_errors_in_disagreement']} "
        f"({caught:.0%}) fall where the two disagree. A reviewer who checks only the "
        f"{1 - o['agree']:.0%} of rows in dispute would see that share of its mistakes — compare "
        "the student-disagreement ranking of [human corrections](correction.md), which needs no "
        "second LLM.",
        "",
        f"**Caveat.** {o['n']} queries: every accuracy here carries about ±5 pt of sampling noise "
        "(95 %), so small differences between the teachers are not findings.",
    ]
    DOCS.mkdir(parents=True, exist_ok=True)
    (DOCS / "second_teacher.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
