"""How much does the served student's accuracy move with the training seed? (roadmap 7.3)

    python scripts/seeds.py                                  # minilm_ft_teacher, seeds 0-2
    python scripts/seeds.py --run distilbert_ft_teacher

6.10's paired bootstrap measured *test-set* noise (which queries happen to be in the test
split). The other half is *seed* noise: retrain the same config with another seed (a different
validation split, head initialisation and batch order) and the accuracy moves too. The Colab
session of 7.3 trains the served config with seeds 1 and 2 next to the published seed 0
(`finetune.py --seed N`, saved as `<run>_s<N>`); this reads them and reports the spread, fp32
and int8, so claims like "MiniLM ties DistilBERT" can be checked against it.

Writes results/seeds.json and docs/seeds.md.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from distilroute.data import DOCS, RESULTS, rel  # noqa: E402

METRICS = [("accuracy", "accuracy (fp32)"), ("accuracy_int8", "accuracy (int8, served)")]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--run", default="minilm_ft_teacher", help="the seed-0 run name")
    args = ap.parse_args()

    base = args.run.rsplit("_", 1)  # minilm_ft_teacher -> minilm_ft, teacher
    runs = {0: RESULTS / f"{args.run}.json"}
    runs |= {
        int(p.stem.split("_s")[-1].split("_")[0]): p
        for p in RESULTS.glob(f"{base[0]}_s*_{base[1]}.json")
        if p.stem.split("_s")[-1].split("_")[0].isdigit()
    }
    found = {s: json.loads(p.read_text()) for s, p in sorted(runs.items()) if p.exists()}
    if len(found) < 2:
        sys.exit(f"need at least two seeds of {args.run}; found {sorted(found)}")

    out = {"run": args.run, "seeds": sorted(found), "per_seed": {}, "summary": {}}
    for s, m in found.items():
        out["per_seed"][s] = {k: m.get(k) for k, _ in METRICS}
    for k, _ in METRICS:
        vals = [m[k] for m in found.values() if m.get(k) is not None]
        if vals:
            out["summary"][k] = {
                "mean": float(np.mean(vals)),
                "sd": float(np.std(vals, ddof=1)) if len(vals) > 1 else None,
                "range": float(max(vals) - min(vals)),
            }
    RESULTS.mkdir(parents=True, exist_ok=True)
    (RESULTS / "seeds.json").write_text(json.dumps(out, indent=2) + "\n")

    lines = [
        f"# Seed noise: `{args.run}`",
        "",
        f"_Generated by `scripts/seeds.py`. The same config trained with seeds {sorted(found)} "
        "(`finetune.py --seed N`: validation split, head initialisation, batch order); accuracy "
        "vs gold on the full test split._",
        "",
        "| seed | " + " | ".join(label for _, label in METRICS) + " |",
        "|---:|" + "---:|" * len(METRICS),
    ]
    for s, m in out["per_seed"].items():
        cells = [f"{m[k]:.3f}" if m[k] is not None else "—" for k, _ in METRICS]
        lines.append(f"| {s} | " + " | ".join(cells) + " |")
    lines.append(
        "| **mean ± sd (range)** | "
        + " | ".join(
            f"**{v['mean']:.3f}** ± {v['sd']:.3f} ({v['range'] * 100:.1f} pt)"
            if (v := out["summary"].get(k)) and v["sd"] is not None
            else "—"
            for k, _ in METRICS
        )
        + " |"
    )
    lines += [
        "",
        "Differences between models smaller than this range are not findings on seed noise "
        "alone, before test-set noise ([bootstrap](bootstrap.md)) is added on top.",
    ]
    DOCS.mkdir(parents=True, exist_ok=True)
    (DOCS / "seeds.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    print(f"-> {rel(RESULTS)}/seeds.json, {rel(DOCS)}/seeds.md")


if __name__ == "__main__":
    main()
