"""Score teacher label files against gold and write docs/teacher.md.

    python scripts/teacher_report.py                       # default set of runs
    python scripts/teacher_report.py test test.gate_v2     # explicit label files

For each run: accuracy, macro-F1, parse-failure rate, top-k coverage (gold anywhere in the
ranked list), and — for the main run — the weakest intents and the most common confusions.
Partial files are scored as-is and flagged with how much of the split they cover.
"""

from __future__ import annotations

import sys
from pathlib import Path

from sklearn.metrics import f1_score

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from distilroute.data import DOCS, LABELS, load_labels, load_split  # noqa: E402

DEFAULT_RUNS = [
    ("test", "main run: gpt-oss-120b, v2 descriptions, top-3, batch 20"),
    ("test.cmp_low_names", "gate: v1 names only"),
    ("test.cmp_low_desc", "gate: v1 descriptions"),
    ("test.cmp_med_desc", "gate: v1 descriptions, medium reasoning"),
    ("test.gate_v2", "gate: v2 descriptions"),
    ("test.gate_v2_top3", "gate: v2 descriptions, top-3"),
    ("test.gate_v2_b50", "gate: v2, batch 50"),
    ("test.gate_v2_b100", "gate: v2, batch 100"),
    ("test.gate_nemotron550", "gate: second teacher nemotron-3-ultra-550b (OpenRouter)"),
]


def score(name: str) -> dict:
    df = load_labels(name)
    split_n = len(load_split(df.split.iloc[0]))
    parsed = df.teacher.notna()
    hit = df.teacher == df.gold
    in_topk = df.apply(lambda r: r.gold in r.ranked, axis=1)
    return {
        "run": name,
        "n": len(df),
        "coverage": len(df) / split_n,
        "accuracy": hit.mean(),
        "macro_f1": f1_score(df.gold, df.teacher.fillna("_none"), average="macro"),
        "unparsed": (~parsed).mean(),
        "topk_hit": in_topk.mean(),
        "k": int(df.ranked.str.len().max()),
        "model": df.model.iloc[0],
        "df": df,
    }


def main() -> None:
    names = sys.argv[1:] or [r for r, _ in DEFAULT_RUNS]
    notes = dict(DEFAULT_RUNS)
    rows = [score(n) for n in names if (LABELS / f"{n}.jsonl").exists()]

    lines = [
        "# Teacher report",
        "",
        "_Generated by `scripts/teacher_report.py`. Accuracy is against human labels on the test "
        "split. Gate runs are the same 200 queries (seed 1). Coverage < 100 % means the file is "
        "still being labelled — and because the test file is sorted by intent, a partial main "
        "run is **not** a random sample._",
        "",
        "| run | model | n | coverage | accuracy | macro-F1 | unparsed | gold in top-k |",
        "|---|---|---:|---:|---:|---:|---:|---:|",
    ]
    for r in rows:
        topk = f"{r['topk_hit']:.3f} (k={r['k']})" if r["k"] > 1 else "—"
        lines.append(
            f"| {notes.get(r['run'], r['run'])} | `{r['model']}` | {r['n']:,} "
            f"| {r['coverage']:.0%} | **{r['accuracy']:.3f}** | {r['macro_f1']:.3f} "
            f"| {r['unparsed']:.1%} | {topk} |"
        )

    main_run = next((r for r in rows if r["run"] == "test"), None)
    if main_run:
        df = main_run["df"]
        per = df.assign(hit=df.teacher == df.gold).groupby("gold").hit.agg(["mean", "size"])
        weakest = per.sort_values("mean").head(8)
        conf = (
            df[df.teacher != df.gold]
            .groupby(["gold", "teacher"])
            .size()
            .sort_values(ascending=False)
            .head(10)
        )
        lines += [
            "",
            "## Main run — where the teacher is weakest",
            "",
            "| intent | accuracy | n |",
            "|---|---:|---:|",
            *[f"| `{i}` | {m:.2f} | {n} |" for i, (m, n) in weakest.iterrows()],
            "",
            "## Main run — most common confusions (gold → teacher)",
            "",
            "| gold | teacher | count |",
            "|---|---|---:|",
            *[f"| `{g}` | `{t}` | {c} |" for (g, t), c in conf.items()],
        ]

    DOCS.mkdir(exist_ok=True)
    out = DOCS / "teacher.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    sys.stdout.reconfigure(encoding="utf-8")  # Windows consoles default to cp1252
    print("\n".join(lines[5:]))
    print(f"\n-> {out.relative_to(out.parents[1])}")


if __name__ == "__main__":
    main()
